### ISSUE TITLE
Miraculous conversion belongs into framework, not into user code

### ISSUE THREAD

**Issue by Oppodelldog** [marcbreitung/problem-search-explorer#1]
https://github.com/marcbreitung/problem-search-explorer/blob/bb9c6ab5d87cf93d14c19885d43389f4f646840b/src/components/Explorer.vue#L58

In my opinion, the user who defines a **problem** and passes this into a **search strategy** should not be responsible of aggregating the solution into another *solution*, just by overwriting the variable.

The duplication of the word **solution** in this context is an indicator that there might be done too much   to achieve what is finally needed.

I experienced that when I was writing a react app using your modules. (which are a very nicely decoupled piece of software, btw)
Me, talking as the user mentioned above, would like to get a reusable result - In my case to simply display it. I would not like to convert the solution into another representation by knowing about the miraculous method **findGraphNodeByState**, whatevery that means. This is some detail that belongs into one of the frameworks components, not into the users code.

I hope I got the point of this code line and gave some useful input.
Since we just talked about this topic at the **cologne developer meeting in the Puszta Hütte** an hour ago, I did not validate the assumptions I made 👍 

Cheers!

**Comment by marcbreitung** [comment]
I added a new method called _solutionGraph()_. This returns the solution as an list of _ProblemSearch.GraphNode_. Now you can inject this list without any converting or mapping in the _Layer_.

Unfortunately I added this changes after I renamed some classes. If your application breaks, please check the console.log() to see which classes you have to rename.
